### ISSUE TITLE
Query regarding possible data contamination

### ISSUE THREAD

**Issue by vardaan123** [thunlp/ERNIE#62]
Thanks for releasing the code. I have a doubt regarding data contamination. I saw that in the Wikidata embeddings made available by you, it includes embeddings of Wikipedia types (like Human, Organization, etc.). In Wikidata, there are triples present that contain the type information (e.g. Barack Obama (Q76), instance of (P31), Human (Q5)) directly. My question is whether you exclude such triples while training the embeddings for the entities whose types are to be predicted in the FIGER/OpenEntity test sets.

**Comment by zzy14** [comment]
Thanks for your question! Sorry for the late reply. We didn't exclude such triples while training KE because entity typing aims to identify the type based on the context. For example, Barack Obama may have several types, such as Human and Politician while only part of types are annotated in a given sentence. However, for relation classification, it is important to exclude the triples in the dataset.

**Comment by vardaan123** [comment]
Ok, cool. Thanks for the explanation.
